searchWords  = [
    "lord store",
    "how to sign up or login",
    "login",
    "sign up",
    "usa", 
    "morocco", 
    "nono" ,
    "love", 
    "javascript tutorial", 
    "python basics", 
    "best photo editing software", 
    "android development", 
    "website design",
    "machine learning",
    "data science",
    "cybersecurity",
    "cloud computing",
    "blockchain technology",
    "quantum computing",
    "augmented reality",
    "virtual reality",
    "internet of things",
    "smartphones",
    "wearable technology",
    "gaming consoles",
    "computer programming",
    "software development",
    "web development",
    "mobile apps",
    "networking",
    "digital marketing",
    "e-commerce",
    "latest movies", 
    "trending music", 
    "top TV shows", 
    "funny videos", 
    "video game reviews",
    "movie reviews",
    "book recommendations",
    "music genres",
    "celebrity gossip",
    "TV show recommendations",
    "streaming services",
    "concert tickets",
    "upcoming movie releases",
    "film festivals",
    "award shows",
    "entertainment news",
    "pop culture trends",
    "celebrity interviews",
    "behind-the-scenes",
    "fan theories",
    "world news headlines", 
    "local news updates",
    "stock market today", 
    "weather forecast",
    "online deals", 
    "product reviews", 
    "best tech gadgets", 
    "fashion trends", 
    "travel destinations",
    "women's dresses", 
    "men's jeans", 
    "laptop deals", 
    "smartphones", 
    "wireless headphones", 
    "coffee makers", 
    "home decor", 
    "bedding sets",
    "nike", 
    "adidas", 
    "apple", 
    "samsung", 
    "sony",
    "gifts under $50", 
    "summer fashion trends", 
    "back to school supplies", 
    "black friday deals", 
    "kitchen gadgets",
    "healthy recipes",
    "fitness workouts",
    "yoga poses",
    "meditation techniques",
    "mental health tips",
    "nutrition guides",
    "weight loss strategies",
    "home workouts",
    "stress relief techniques",
    "sleep hygiene",
    "mindfulness practices",
    "healthy eating",
    "exercise routines",
    "wellness retreats",
    "medical conditions",
    "alternative medicine",
    "self-care practices",
    "budget travel tips",
    "solo travel advice",
    "family vacation ideas",
    "adventure travel",
    "cultural experiences",
    "backpacking tips",
    "road trip essentials",
    "luxury travel",
    "travel hacks",
    "travel insurance",
    "flight deals",
    "hotel accommodations",
    "tourist attractions",
    "local cuisine",
    "travel blogs",
    "personal finance",
    "investment strategies",
    "saving money tips",
    "credit card rewards",
    "retirement planning",
    "financial independence",
    "budgeting techniques",
    "tax planning",
    "side hustle ideas",
    "passive income streams",
    "wealth management",
    "financial literacy",
    "debt management",
    "mortgage options",
    "stock market",
    "study tips",
    "test preparation",
    "language learning",
    "coding tutorials",
    "academic resources",
    "career development",
    "college admissions",
    "student loans",
    "scholarship opportunities",
    "educational technology",
    "learning platforms",
    "distance learning",
    "tutoring services",
    "academic programs",
    "home organization",
    "DIY projects",
    "interior design",
    "gardening tips",
    "cooking techniques",
    "parenting advice",
    "pet care tips",
    "relationship advice",
    "self-improvement",
    "productivity hacks",
    "time management",
    "stress management",
    "hobby ideas",
    "travel photography",
    "fashion trends",
    "beauty tips",
    "wellness routines",
    "programming languages",
    "web development frameworks",
    "data analysis tools",
    "graphic design software",
    "mobile app development",
    "cloud storage services",
    "video editing software",
    "cybersecurity measures",
    "virtual private networks",
    "digital marketing strategies",
    "e-commerce platforms",
    "celebrity news",
    "music festivals",
    "stand-up comedy specials",
    "documentary recommendations",
    "TV series binge-watching",
    "movie streaming platforms",
    "album reviews",
    "gaming communities",
    "comic book adaptations",
    "award-winning films",
    "political news",
    "global economy updates",
    "business trends",
    "social media controversies",
    "environmental issues",
    "scientific discoveries",
    "space exploration news",
    "sports highlights",
    "healthcare reforms",
    "education policies",
    "online shopping tips",
    "discount codes",
    "fashion accessories",
    "home improvement tools",
    "kitchen appliances",
    "travel essentials",
    "outdoor gear",
    "pet supplies",
    "tech accessories",
    "book recommendations",
    "healthy meal plans",
    "fitness challenges",
    "mind-body exercises",
    "stress management techniques",
    "natural remedies",
    "mental health resources",
    "sleep improvement methods",
    "wellness retreat locations",
    "mindfulness apps",
    "alternative therapies",
    "sustainable travel practices",
    "off-the-beaten-path destinations",
    "cultural immersion experiences",
    "adventure sports",
    "road trip itineraries",
    "luxury accommodations",
    "budget-friendly travel hacks",
    "travel photography tips",
    "backpacking gear recommendations",
    "travel safety advice",
    "investment opportunities",
    "savings accounts",
    "credit score improvement",
    "retirement savings plans",
    "tax-saving strategies",
    "budgeting apps",
    "passive income ideas",
    "real estate investment tips",
    "stock market analysis",
    "cryptocurrency trends",
    "online learning platforms",
    "study abroad programs",
    "test-taking strategies",
    "language exchange communities",
    "coding bootcamps",
    "scholarship search engines",
    "career exploration resources",
    "professional development courses",
    "educational podcasts",
    "academic research databases",
    "self-care routines",
    "home workout plans",
    "creative hobbies",
    "mindfulness practices",
    "family bonding activities",
    "sustainable living tips",
    "relationship-building exercises",
    "time management techniques",
    "personal development books",
    "organization hacks"
];
  


